# Generated by Django 5.2.11 on 2026-02-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_rename_jobs_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
