# Generated by Django 5.2.11 on 2026-03-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_alter_client_email_alter_client_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='location',
            field=models.CharField(blank=True, choices=[('N', 'North'), ('NE', 'Northeast'), ('NW', 'Northwest'), ('S', 'South'), ('SW', 'Southwest'), ('SE', 'Southeast'), ('OH', 'Ohio')], default='OH', max_length=2),
        ),
    ]
