# Generated by Django 5.2.11 on 2026-03-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_client_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
