# Generated by Django 5.2.11 on 2026-03-04 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_alter_job_scheduled_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='type',
        ),
    ]
