# Generated by Django 5.2.11 on 2026-03-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
