# Generated by Django 5.2.11 on 2026-03-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_alter_scheduler_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, help_text='Full street address'),
        ),
    ]
